import type { ChatCompletionTool } from 'openai/resources/chat/completions';
const s=(properties:Record<string,unknown>,required:string[]=[]):any=>({type:'object',additionalProperties:false,properties,required});
export const VOICE_V2_TOOLS: ChatCompletionTool[]=[
{type:'function',function:{name:'create_party',description:'Create a customer or supplier.',parameters:s({name:{type:'string'},partyType:{type:'string',enum:['CUSTOMER','SUPPLIER']},phone:{type:['string','null']}},['name','partyType','phone'])}},
{type:'function',function:{name:'get_party',description:'Find one customer or supplier and return details and balance.',parameters:s({name:{type:'string'},partyType:{type:['string','null'],enum:['CUSTOMER','SUPPLIER',null]}},['name','partyType'])}},
{type:'function',function:{name:'list_parties',description:'List customers or suppliers.',parameters:s({partyType:{type:['string','null'],enum:['CUSTOMER','SUPPLIER',null]}},['partyType'])}},
{type:'function',function:{name:'update_party',description:'Update a customer or supplier.',parameters:s({name:{type:'string'},newName:{type:['string','null']},phone:{type:['string','null']},partyType:{type:['string','null'],enum:['CUSTOMER','SUPPLIER',null]}},['name','newName','phone','partyType'])}},
{type:'function',function:{name:'delete_party',description:'Delete a customer or supplier. Use only when explicitly requested.',parameters:s({name:{type:'string'}},['name'])}},
{type:'function',function:{name:'create_product',description:'Create a product/inventory item.',parameters:s({name:{type:'string'},unit:{type:'string'},stockQuantity:{type:'number'},buyPrice:{type:'number'},sellPrice:{type:'number'},lowStockThreshold:{type:'number'}},['name','unit','stockQuantity','buyPrice','sellPrice','lowStockThreshold'])}},
{type:'function',function:{name:'get_product',description:'Find a product and return stock/prices.',parameters:s({name:{type:'string'}},['name'])}},
{type:'function',function:{name:'list_products',description:'List products/inventory.',parameters:s({},[])}},
{type:'function',function:{name:'update_product',description:'Update a product.',parameters:s({name:{type:'string'},newName:{type:['string','null']},unit:{type:['string','null']},stockQuantity:{type:['number','null']},buyPrice:{type:['number','null']},sellPrice:{type:['number','null']},lowStockThreshold:{type:['number','null']}},['name','newName','unit','stockQuantity','buyPrice','sellPrice','lowStockThreshold'])}},
{type:'function',function:{name:'delete_product',description:'Delete a product. Use only when explicitly requested.',parameters:s({name:{type:'string'}},['name'])}},
{type:'function',function:{name:'create_transaction',description:'Create a ledger transaction.',parameters:s({type:{type:'string',enum:['DUE_GIVEN','DUE_RECEIVED','STOCK_IN','STOCK_OUT','EXPENSE','SALE']},partyName:{type:['string','null']},productName:{type:['string','null']},amount:{type:'number'},quantity:{type:'number'},unitPrice:{type:['number','null']},paidAmount:{type:['number','null']},notes:{type:['string','null']}},['type','partyName','productName','amount','quantity','unitPrice','paidAmount','notes'])}},
{type:'function',function:{name:'get_balance',description:'Answer how much a party owes or is owed. Read database balance.',parameters:s({name:{type:'string'}},['name'])}},
{type:'function',function:{name:'search_transactions',description:'Search recent ledger transactions.',parameters:s({query:{type:['string','null']},limit:{type:'number'}},['query','limit'])}},
{type:'function',function:{name:'delete_transaction',description:'Delete/reverse a ledger transaction. Use only when explicitly requested.',parameters:s({id:{type:['string','null']},partyName:{type:['string','null']},amount:{type:['number','null']}},['id','partyName','amount'])}},
{type:'function',function:{name:'list_users',description:'ADMIN ONLY: list application users.',parameters:s({},[])}},
{type:'function',function:{name:'create_user',description:'ADMIN ONLY: create a user account.',parameters:s({name:{type:'string'},email:{type:'string'},phone:{type:['string','null']},role:{type:'string',enum:['USER','ADMIN']},status:{type:'string',enum:['ACTIVE','SUSPENDED']}},['name','email','phone','role','status'])}},
{type:'function',function:{name:'update_user',description:'ADMIN ONLY: update a user.',parameters:s({email:{type:'string'},name:{type:['string','null']},phone:{type:['string','null']},status:{type:['string','null'],enum:['ACTIVE','SUSPENDED',null]},role:{type:['string','null'],enum:['USER','ADMIN',null]}},['email','name','phone','status','role'])}},
{type:'function',function:{name:'delete_user',description:'ADMIN ONLY: delete a user. Never delete current admin.',parameters:s({email:{type:'string'}},['email'])}}
];
export const VOICE_V2_SYSTEM='You are TaliKhata Voice Engine V2. Understand Bengali, Banglish, English, Bengali/English digits and mixed speech. Always use a tool for database actions or database questions; never invent database facts. Preserve spoken names. Possessive suffixes are not part of names: করিমের/করিমকে/korimer/korim er/korim ke refer to করিম. করিমকে 300 টাকা দিলাম means DUE_GIVEN. করিম 300 টাকা দিল or করিমের কাছ থেকে 300 টাকা পেলাম means DUE_RECEIVED. করিমের কাছে কত টাকা পাব and korimer kache koto taka pabo mean get_balance. Choose the narrowest CRUD tool. Never invent missing values. Destructive actions require server confirmation.';