'use client';

import {useEffect,useMemo,useState} from 'react';
import {AlertTriangle,Barcode,Boxes,CheckCircle2,ChevronDown,Layers3,Loader2,Package,Pencil,Plus,Search,Store,Tag,Trash2,X} from 'lucide-react';

type BusinessType='GENERAL_RETAIL'|'GROCERY'|'CLOTHING'|'ELECTRONICS'|'PHARMACY'|'RESTAURANT'|'WHOLESALE'|'SERVICE'|'HARDWARE'|'OTHER';
type Variant={uiId:string;name:string;sku:string;barcode:string;attributes:string;stockQuantity:number;buyPrice:number;sellPrice:number};
type Product={_id:string;name:string;category?:string;brand?:string;sku?:string;barcode?:string;unit:string;stockQuantity:number;buyPrice:number;sellPrice:number;lowStockThreshold:number;trackStock?:boolean;attributes?:Record<string,string|number|boolean>;variants?:Array<{_id?:string;name:string;sku?:string;barcode?:string;attributes?:Record<string,string|number|boolean>;stockQuantity:number;buyPrice:number;sellPrice:number}>};

const businessLabels:Record<BusinessType,string>={GENERAL_RETAIL:'General retail',GROCERY:'Grocery',CLOTHING:'Clothing & fashion',ELECTRONICS:'Electronics',PHARMACY:'Pharmacy',RESTAURANT:'Restaurant / food',WHOLESALE:'Wholesale',SERVICE:'Service business',HARDWARE:'Hardware',OTHER:'Other'};
const categorySuggestions:Record<BusinessType,string[]>={GENERAL_RETAIL:['General','Daily essentials','Other'],GROCERY:['Rice & grains','Oil & spices','Snacks','Beverages','Household','Other'],CLOTHING:['Men','Women','Kids','Shoes','Accessories','Other'],ELECTRONICS:['Mobile','Accessories','Computer','Appliances','Other'],PHARMACY:['Medicine','OTC','Personal care','Medical supplies','Other'],RESTAURANT:['Food','Drinks','Combo','Dessert','Other'],WHOLESALE:['General','Distributor','Bulk goods','Other'],SERVICE:['Labour','Repair','Installation','Other'],HARDWARE:['Tools','Electrical','Plumbing','Building materials','Other'],OTHER:['General','Other']};
const units=['pcs','kg','g','liter','ml','meter','box','pack','pair','dozen','hour','service'];

const emptyForm={name:'',category:'',brand:'',sku:'',barcode:'',unit:'pcs',stockQuantity:0,buyPrice:0,sellPrice:0,lowStockThreshold:5,trackStock:true,attributes:[] as Array<{key:string;value:string}>,variants:[] as Variant[]};

function makeVariant():Variant{return {uiId:'v-'+Date.now()+'-'+Math.random().toString(36).slice(2,7),name:'',sku:'',barcode:'',attributes:'',stockQuantity:0,buyPrice:0,sellPrice:0}}

function FieldIcon({children}:{children:React.ReactNode}){return <span className="pointer-events-none absolute left-3.5 top-1/2 -translate-y-1/2 text-slate-400">{children}</span>}

function Toast({toast,onClose}:{toast:{type:'success'|'error';message:string}|null;onClose:()=>void}){if(!toast)return null;return <div className="fixed inset-x-4 bottom-24 z-[100] flex justify-center md:bottom-6 md:inset-x-auto md:right-6 md:w-[380px]" role="status" aria-live="polite"><div className={'flex w-full items-center gap-3 rounded-2xl border bg-white/95 px-4 py-3.5 shadow-2xl backdrop-blur-xl '+(toast.type==='success'?'border-emerald-200':'border-red-200')}><span className={'flex h-9 w-9 shrink-0 items-center justify-center rounded-full '+(toast.type==='success'?'bg-emerald-100 text-emerald-600':'bg-red-100 text-red-600')}>{toast.type==='success'?<CheckCircle2 size={19}/>:<AlertTriangle size={19}/>}</span><p className="min-w-0 flex-1 text-sm font-semibold text-slate-800">{toast.message}</p><button type="button" onClick={onClose} className="rounded-full p-1.5 text-slate-400 hover:bg-slate-100" aria-label="Close notification"><X size={16}/></button></div></div>}

function DeleteModal({name,busy,onCancel,onConfirm}:{name:string;busy:boolean;onCancel:()=>void;onConfirm:()=>void}){return <div className="fixed inset-0 z-[90] flex items-center justify-center bg-slate-950/35 px-4 backdrop-blur-sm" role="dialog" aria-modal="true"><div className="w-full max-w-md rounded-[28px] border border-white/70 bg-white p-5 shadow-2xl sm:p-6"><div className="flex items-start gap-3"><span className="flex h-11 w-11 shrink-0 items-center justify-center rounded-full bg-red-50 text-red-600"><Trash2 size={20}/></span><div className="min-w-0 flex-1"><h2 className="text-lg font-bold text-slate-900">Delete product?</h2><p className="mt-1 text-sm leading-6 text-slate-500">“{name}” will be removed if it has no transaction history. Existing ledger history is protected.</p></div><button type="button" onClick={onCancel} className="rounded-full p-2 text-slate-400 hover:bg-slate-100" aria-label="Close dialog"><X size={18}/></button></div><div className="mt-5 flex flex-col-reverse gap-2 sm:flex-row sm:justify-end"><button type="button" onClick={onCancel} className="btn-secondary w-full sm:w-auto">Cancel</button><button type="button" disabled={busy} onClick={onConfirm} className="flex w-full items-center justify-center gap-2 rounded-xl bg-red-600 px-4 py-2.5 text-sm font-semibold text-white hover:bg-red-700 disabled:opacity-60 sm:w-auto">{busy&&<Loader2 size={16} className="animate-spin"/>}{busy?'Deleting…':'Delete product'}</button></div></div></div>}

export default function ProductsPage(){
 const[rows,setRows]=useState<Product[]>([]);const[form,setForm]=useState<typeof emptyForm>(emptyForm);const[editing,setEditing]=useState<string|null>(null);const[q,setQ]=useState('');const[error,setError]=useState('');const[busy,setBusy]=useState(false);const[loading,setLoading]=useState(true);const[shopType,setShopType]=useState<BusinessType>('GENERAL_RETAIL');const[toast,setToast]=useState<{type:'success'|'error';message:string}|null>(null);const[deleteTarget,setDeleteTarget]=useState<Product|null>(null);const[showAdvanced,setShowAdvanced]=useState(false);
 const load=async()=>{try{const r=await fetch('/api/products'+(q?'?q='+encodeURIComponent(q):''),{cache:'no-store'});const d=await r.json();if(!r.ok)throw new Error(typeof d?.error==='string'?d.error:'Could not load products');setRows(Array.isArray(d)?d:[])}catch(e){setError(e instanceof Error?e.message:'Could not load products')}finally{setLoading(false)}};
 useEffect(()=>{void load()},[q]);useEffect(()=>{const h=()=>void load();window.addEventListener('talikhata:refresh',h);return()=>window.removeEventListener('talikhata:refresh',h)},[]);useEffect(()=>{fetch('/api/shop',{cache:'no-store'}).then(r=>r.ok?r.json():null).then(d=>{if(d?.businessType)setShopType(d.businessType as BusinessType)}).catch(()=>{})},[]);useEffect(()=>{if(!toast)return;const t=setTimeout(()=>setToast(null),3600);return()=>clearTimeout(t)},[toast]);
 const low=useMemo(()=>rows.filter(x=>x.trackStock!==false&&x.stockQuantity<=x.lowStockThreshold).length,[rows]);
 function reset(){setForm({...emptyForm,attributes:[],variants:[]});setEditing(null);setError('');setShowAdvanced(false)}
 function startEdit(p:Product){setEditing(p._id);setError('');setShowAdvanced(Boolean(p.category||p.brand||p.sku||p.barcode||(p.attributes&&Object.keys(p.attributes).length)||(p.variants?.length)));setForm({name:p.name,category:p.category||'',brand:p.brand||'',sku:p.sku||'',barcode:p.barcode||'',unit:p.unit,stockQuantity:p.stockQuantity,buyPrice:p.buyPrice,sellPrice:p.sellPrice,lowStockThreshold:p.lowStockThreshold,trackStock:p.trackStock!==false,attributes:Object.entries(p.attributes||{}).map(([key,value])=>({key,value:String(value)})),variants:(p.variants||[]).map(v=>({uiId:v._id||makeVariant().uiId,name:v.name,sku:v.sku||'',barcode:v.barcode||'',attributes:Object.entries(v.attributes||{}).map(([k,val])=>k+'='+val).join(', '),stockQuantity:v.stockQuantity,buyPrice:v.buyPrice,sellPrice:v.sellPrice}))});window.scrollTo({top:0,behavior:'smooth'})}
 function updateAttribute(index:number,key:'key'|'value',value:string){setForm(f=>({...f,attributes:f.attributes.map((a,i)=>i===index?{...a,[key]:value}:a)}))}
 function updateVariant(index:number,key:keyof Variant,value:string|number){setForm(f=>({...f,variants:f.variants.map((v,i)=>i===index?{...v,[key]:value}:v)}))}
 async function save(e:React.FormEvent){e.preventDefault();setError('');setBusy(true);try{const attributes=Object.fromEntries(form.attributes.filter(x=>x.key.trim()).map(x=>[x.key.trim(),x.value.trim()]));const variants=form.variants.filter(v=>v.name.trim()).map(v=>({name:v.name.trim(),sku:v.sku.trim()||undefined,barcode:v.barcode.trim()||undefined,attributes:Object.fromEntries(v.attributes.split(',').map(x=>x.trim()).filter(Boolean).map(x=>{const parts=x.split('=');return [parts[0].trim(),parts.slice(1).join('=').trim()]}).filter(x=>x[0])),stockQuantity:Number(v.stockQuantity)||0,buyPrice:Number(v.buyPrice)||0,sellPrice:Number(v.sellPrice)||0}));const payload={name:form.name.trim(),category:form.category.trim()||undefined,brand:form.brand.trim()||undefined,sku:form.sku.trim()||undefined,barcode:form.barcode.trim()||undefined,unit:form.unit,stockQuantity:Number(form.stockQuantity)||0,buyPrice:Number(form.buyPrice)||0,sellPrice:Number(form.sellPrice)||0,lowStockThreshold:Number(form.lowStockThreshold)||0,trackStock:form.trackStock,attributes,variants};const r=await fetch(editing?'/api/products/'+editing:'/api/products',{method:editing?'PATCH':'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload)});const d=await r.json().catch(()=>null);if(!r.ok)throw new Error(typeof d?.error==='string'?d.error:'Could not save product');setToast({type:'success',message:editing?'Product updated successfully.':'Product added successfully.'});reset();await load();window.dispatchEvent(new Event('talikhata:refresh'))}catch(e){setError(e instanceof Error?e.message:'Could not save product')}finally{setBusy(false)}}
 async function remove(){if(!deleteTarget)return;setBusy(true);try{const r=await fetch('/api/products/'+deleteTarget._id,{method:'DELETE'});const d=await r.json().catch(()=>null);if(!r.ok)throw new Error(typeof d?.error==='string'?d.error:'Could not delete product');setDeleteTarget(null);setToast({type:'success',message:deleteTarget.name+' deleted successfully.'});await load();window.dispatchEvent(new Event('talikhata:refresh'))}catch(e){setToast({type:'error',message:e instanceof Error?e.message:'Could not delete product'})}finally{setBusy(false)}}

 return <div className="mx-auto w-full max-w-6xl pb-36 md:pb-10"><Toast toast={toast} onClose={()=>setToast(null)}/>{deleteTarget&&<DeleteModal name={deleteTarget.name} busy={busy} onCancel={()=>!busy&&setDeleteTarget(null)} onConfirm={()=>void remove()}/>}
  <header className="mb-6 flex flex-col gap-4 px-1 sm:flex-row sm:items-end sm:justify-between"><div><div className="mb-2 flex items-center gap-2 text-emerald-600"><Boxes size={17}/><span className="text-xs font-bold uppercase tracking-[0.12em]">Inventory</span></div><h1 className="text-[28px] font-bold tracking-[-0.04em] text-slate-900 sm:text-3xl">পণ্য ও স্টক</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-500">Business-aware catalog for {businessLabels[shopType]}. Categories, brands, SKUs, barcodes and variants work inside the existing ledger.</p></div>{low>0&&<span className="inline-flex w-fit items-center gap-2 rounded-2xl bg-amber-50 px-3.5 py-2.5 text-sm font-semibold text-amber-700"><AlertTriangle size={16}/>{low} low-stock item{low===1?'':'s'}</span>}</header>
  <div className="grid gap-5 lg:grid-cols-[390px_minmax(0,1fr)]">
   <form onSubmit={save} className="rounded-[28px] border border-white/80 bg-white/80 p-4 shadow-[0_8px_32px_rgba(31,38,135,0.07)] backdrop-blur-xl sm:p-5">
    <div className="mb-5 flex items-center justify-between gap-3"><div className="flex min-w-0 items-center gap-3"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-full bg-emerald-500/10 text-emerald-600"><Package size={19}/></span><div className="min-w-0"><h2 className="truncate font-bold text-slate-900">{editing?'Edit product':'Add product'}</h2><p className="text-xs text-slate-500">{businessLabels[shopType]}</p></div></div>{editing&&<button type="button" onClick={reset} className="rounded-full p-2 text-slate-400 hover:bg-slate-100" aria-label="Cancel editing"><X size={18}/></button>}</div>
    <div className="space-y-4">
     <div><label className="form-label" htmlFor="product-name">Product name</label><div className="relative"><FieldIcon><Package size={16}/></FieldIcon><input id="product-name" className="field pl-10" value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="e.g. Premium T-shirt" required/></div></div>
     <div className="grid gap-3 sm:grid-cols-2"><div><label className="form-label" htmlFor="product-category">Category</label><div className="relative"><FieldIcon><Layers3 size={16}/></FieldIcon><input id="product-category" list="category-options" className="field pl-10" value={form.category} onChange={e=>setForm({...form,category:e.target.value})} placeholder="Select or type"/></div><datalist id="category-options">{categorySuggestions[shopType].map(x=><option key={x} value={x}/>)}</datalist></div><div><label className="form-label" htmlFor="product-brand">Brand</label><div className="relative"><FieldIcon><Tag size={16}/></FieldIcon><input id="product-brand" className="field pl-10" value={form.brand} onChange={e=>setForm({...form,brand:e.target.value})} placeholder="Brand name"/></div></div></div>
     <div className="grid gap-3 sm:grid-cols-2"><div><label className="form-label" htmlFor="product-unit">Unit</label><div className="relative"><FieldIcon><ChevronDown size={16}/></FieldIcon><select id="product-unit" className="field appearance-none pl-10" value={form.unit} onChange={e=>setForm({...form,unit:e.target.value})}>{units.map(u=><option key={u}>{u}</option>)}</select></div></div><div><label className="form-label" htmlFor="product-stock">Opening stock</label><input id="product-stock" className="field" type="number" min="0" step="0.01" value={form.stockQuantity} onChange={e=>setForm({...form,stockQuantity:Number(e.target.value)})}/></div></div>
     <div className="grid gap-3 sm:grid-cols-2"><div><label className="form-label" htmlFor="buy-price">Buy price (৳)</label><input id="buy-price" className="field" type="number" min="0" step="0.01" value={form.buyPrice} onChange={e=>setForm({...form,buyPrice:Number(e.target.value)})}/></div><div><label className="form-label" htmlFor="sell-price">Sell price (৳)</label><input id="sell-price" className="field" type="number" min="0" step="0.01" value={form.sellPrice} onChange={e=>setForm({...form,sellPrice:Number(e.target.value)})}/></div></div>
     <label className="flex cursor-pointer items-center justify-between rounded-2xl border border-slate-200 bg-slate-50/70 px-3.5 py-3"><span><span className="block text-sm font-semibold text-slate-800">Track stock</span><span className="text-xs text-slate-500">Update inventory automatically after sales</span></span><input type="checkbox" className="h-4 w-4 accent-emerald-600" checked={form.trackStock} onChange={e=>setForm({...form,trackStock:e.target.checked})}/></label>
     <button type="button" onClick={()=>setShowAdvanced(v=>!v)} className="flex w-full items-center justify-between rounded-2xl border border-slate-200 px-3.5 py-3 text-left hover:bg-slate-50"><span className="flex items-center gap-2 text-sm font-semibold text-slate-800"><Store size={16}/> Business details</span><ChevronDown size={17} className={showAdvanced?'rotate-180 transition-transform':'transition-transform'}/></button>
     {showAdvanced&&<div className="space-y-4 rounded-2xl bg-slate-50/70 p-3.5">
      <div className="grid gap-3 sm:grid-cols-2"><div><label className="form-label" htmlFor="product-sku">SKU</label><div className="relative"><FieldIcon><Tag size={16}/></FieldIcon><input id="product-sku" className="field pl-10" value={form.sku} onChange={e=>setForm({...form,sku:e.target.value})} placeholder="e.g. TS-BLK-M"/></div></div><div><label className="form-label" htmlFor="product-barcode">Barcode</label><div className="relative"><FieldIcon><Barcode size={16}/></FieldIcon><input id="product-barcode" className="field pl-10" value={form.barcode} onChange={e=>setForm({...form,barcode:e.target.value})} placeholder="Scan or type barcode"/></div></div></div>
      <div><div className="mb-2 flex items-center justify-between"><label className="text-xs font-semibold text-slate-600">Custom attributes</label><button type="button" onClick={()=>setForm(f=>({...f,attributes:[...f.attributes,{key:'',value:''}]}))} className="text-xs font-semibold text-emerald-600">+ Add field</button></div><div className="space-y-2">{form.attributes.map((a,i)=><div key={i} className="grid grid-cols-[1fr_1fr_auto] gap-2"><input className="field" placeholder="Key e.g. material" value={a.key} onChange={e=>updateAttribute(i,'key',e.target.value)}/><input className="field" placeholder="Value e.g. cotton" value={a.value} onChange={e=>updateAttribute(i,'value',e.target.value)}/><button type="button" onClick={()=>setForm(f=>({...f,attributes:f.attributes.filter((_,idx)=>idx!==i)}))} className="rounded-xl p-2 text-slate-400 hover:bg-white hover:text-red-500" aria-label="Remove attribute"><X size={16}/></button></div>)}{!form.attributes.length&&<p className="text-xs text-slate-400">Use fields such as color, material, warranty or expiry.</p>}</div></div>
      <div><div className="mb-2 flex items-center justify-between"><div><label className="text-xs font-semibold text-slate-600">Variants</label><p className="text-[11px] text-slate-400">Size, color, model or package combinations.</p></div><button type="button" onClick={()=>setForm(f=>({...f,variants:[...f.variants,makeVariant()]}))} className="inline-flex items-center gap-1.5 text-xs font-semibold text-emerald-600"><Plus size={14}/> Add variant</button></div><div className="space-y-3">{form.variants.map((v,i)=><div key={v.uiId} className="rounded-2xl border border-slate-200 bg-white p-3"><div className="mb-2 flex items-center justify-between"><span className="text-xs font-bold text-slate-700">Variant {i+1}</span><button type="button" onClick={()=>setForm(f=>({...f,variants:f.variants.filter(x=>x.uiId!==v.uiId)}))} className="rounded-full p-1.5 text-slate-400 hover:bg-red-50 hover:text-red-500" aria-label="Remove variant"><X size={15}/></button></div><div className="grid gap-2 sm:grid-cols-2"><input className="field" placeholder="Name e.g. Black / M" value={v.name} onChange={e=>updateVariant(i,'name',e.target.value)}/><input className="field" placeholder="Variant SKU" value={v.sku} onChange={e=>updateVariant(i,'sku',e.target.value)}/><input className="field" placeholder="Barcode" value={v.barcode} onChange={e=>updateVariant(i,'barcode',e.target.value)}/><input className="field" placeholder="size=M, color=Black" value={v.attributes} onChange={e=>updateVariant(i,'attributes',e.target.value)}/><input className="field" type="number" min="0" step="0.01" placeholder="Stock" value={v.stockQuantity} onChange={e=>updateVariant(i,'stockQuantity',Number(e.target.value))}/><input className="field" type="number" min="0" step="0.01" placeholder="Buy price" value={v.buyPrice} onChange={e=>updateVariant(i,'buyPrice',Number(e.target.value))}/><input className="field sm:col-span-2" type="number" min="0" step="0.01" placeholder="Sell price" value={v.sellPrice} onChange={e=>updateVariant(i,'sellPrice',Number(e.target.value))}/></div></div>)}{!form.variants.length&&<p className="rounded-xl border border-dashed border-slate-200 px-3 py-3 text-xs text-slate-400">No variants. Add them when one product has multiple sizes, colors or models.</p>}</div></div>
     </div>}
     <div><label className="form-label" htmlFor="low-stock">Low-stock threshold</label><input id="low-stock" className="field" type="number" min="0" step="0.01" value={form.lowStockThreshold} onChange={e=>setForm({...form,lowStockThreshold:Number(e.target.value)})}/></div>
     {error&&<div className="rounded-2xl border border-red-200 bg-red-50 px-3.5 py-3 text-sm font-medium leading-5 text-red-700" role="alert">{error}</div>}
     <div className="flex flex-col gap-2 sm:flex-row"><button disabled={busy} aria-busy={busy} className="btn-primary flex-1">{busy?<Loader2 size={17} className="animate-spin"/>:<Plus size={17}/>} {busy?(editing?'Updating…':'Adding…'):(editing?'Update product':'Add product')}</button>{editing&&<button type="button" disabled={busy} onClick={reset} className="btn-secondary">Cancel</button>}</div>
    </div>
   </form>
   <section className="min-w-0 rounded-[28px] border border-white/80 bg-white/80 p-4 shadow-[0_8px_32px_rgba(31,38,135,0.07)] backdrop-blur-xl sm:p-5">
    <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="font-bold text-slate-900">Inventory</h2><p className="text-xs text-slate-500">{rows.length} product{rows.length===1?'':'s'}</p></div><div className="relative w-full sm:w-72"><FieldIcon><Search size={16}/></FieldIcon><input className="field pl-10" aria-label="Search product" placeholder="Search name, SKU, barcode..." value={q} onChange={e=>setQ(e.target.value)}/></div></div>
    {loading?<div className="mt-5 space-y-3">{[1,2,3,4].map(i=><div key={i} className="h-24 animate-pulse rounded-2xl bg-slate-100"/>)}</div>:<div className="mt-5 space-y-3">{rows.map(r=>{const isLow=r.trackStock!==false&&r.stockQuantity<=r.lowStockThreshold;return <article key={r._id} className="rounded-2xl border border-slate-200 bg-white p-3.5 transition hover:border-slate-300 hover:shadow-sm sm:p-4"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><h3 className="truncate font-semibold text-slate-900">{r.name}</h3>{r.brand&&<span className="rounded-lg bg-slate-100 px-2 py-1 text-[10px] font-semibold text-slate-500">{r.brand}</span>}{r.category&&<span className="rounded-lg bg-emerald-50 px-2 py-1 text-[10px] font-semibold text-emerald-700">{r.category}</span>}</div><p className="mt-1 text-xs text-slate-500">{r.sku?'SKU: '+r.sku+' · ':''}৳{Number(r.sellPrice).toLocaleString('en-BD')} sell · ৳{Number(r.buyPrice).toLocaleString('en-BD')} buy</p>{r.variants?.length?<p className="mt-1 flex items-center gap-1.5 text-[11px] font-medium text-blue-600"><Layers3 size={13}/>{r.variants.length} variant{r.variants.length===1?'':'s'}</p>:null}</div><div className="flex shrink-0 items-center gap-1"><button type="button" onClick={()=>startEdit(r)} className="rounded-xl p-2 text-slate-500 hover:bg-slate-100" aria-label={'Edit '+r.name}><Pencil size={17}/></button><button type="button" onClick={()=>setDeleteTarget(r)} className="rounded-xl p-2 text-red-500 hover:bg-red-50" aria-label={'Delete '+r.name}><Trash2 size={17}/></button></div></div><div className="mt-3 flex flex-wrap items-center justify-between gap-2 border-t border-slate-100 pt-3"><span className={'inline-flex items-center gap-1.5 rounded-xl px-2.5 py-1.5 text-xs font-bold '+(isLow?'bg-amber-50 text-amber-700':'bg-emerald-50 text-emerald-700')}>{isLow&&<AlertTriangle size={13}/>} {r.stockQuantity} {r.unit}</span><span className="text-[11px] text-slate-400">{r.barcode?'Barcode: '+r.barcode:'No barcode'}</span></div></article>})}{!rows.length&&<div className="py-16 text-center"><Boxes size={28} className="mx-auto text-slate-300"/><p className="mt-3 text-sm font-semibold text-slate-600">No products found</p><p className="mt-1 text-xs text-slate-400">Add your first product using the form.</p></div>}</div>}
   </section>
  </div>
 </div>;
}
