'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import {Bell,Check,Loader2,X} from 'lucide-react';
import {motion,AnimatePresence} from 'framer-motion';
type NotificationItem={_id:string;title:string;message:string;read:boolean;createdAt:string};
function relativeTime(value:string){const diff=Math.max(0,Date.now()-new Date(value).getTime());const mins=Math.floor(diff/60000);if(mins<1)return 'এখনই';if(mins<60)return mins+' মিনিট আগে';const hours=Math.floor(mins/60);if(hours<24)return hours+' ঘণ্টা আগে';return Math.floor(hours/24)+' দিন আগে';}
export default function NotificationBell(){
const [items,setItems]=useState<NotificationItem[]>([]);const [open,setOpen]=useState(false);const [loading,setLoading]=useState(false);const ref=useRef<HTMLDivElement>(null);
const load=useCallback(async()=>{try{setLoading(true);const r=await fetch('/api/notifications',{cache:'no-store'});if(r.ok)setItems(await r.json())}catch{}finally{setLoading(false)}},[]);
useEffect(()=>{void load();const id=window.setInterval(()=>{if(document.visibilityState==='visible')void load()},60000);const close=(e:MouseEvent)=>{if(ref.current&&!ref.current.contains(e.target as Node))setOpen(false)};document.addEventListener('mousedown',close);return()=>{window.clearInterval(id);document.removeEventListener('mousedown',close)}},[load]);
const unread=items.filter(x=>!x.read).length;
async function markRead(id?:string){try{await fetch('/api/notifications',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify(id?{id}:{})});setItems(prev=>prev.map(x=>id&&x._id!==id?x:{...x,read:true}))}catch{}}
return <div ref={ref} className="relative">
<button type="button" onClick={()=>setOpen(v=>!v)} className="tk-icon-button relative" aria-label={unread?unread+' unread notifications':'Notifications'} aria-expanded={open}><Bell size={19}/>{unread>0&&<motion.span initial={{scale:0}} animate={{scale:1}} className="absolute -right-0.5 -top-0.5 flex min-h-4 min-w-4 items-center justify-center rounded-full bg-red-500 px-1 text-[9px] font-bold text-white ring-2 ring-[#091540]">{unread>9?'9+':unread}</motion.span>}</button>
<AnimatePresence>{open&&<motion.div initial={{opacity:0,y:-6,scale:.98}} animate={{opacity:1,y:0,scale:1}} exit={{opacity:0,y:-6,scale:.98}} className="fixed inset-x-3 top-[68px] z-[2147483000] mx-auto w-[calc(100vw-1.5rem)] max-w-[380px] overflow-hidden rounded-2xl border border-white/10 bg-[#091540]/98 shadow-2xl backdrop-blur-[36px] sm:inset-x-auto sm:right-3 sm:top-16 sm:mx-0 tk-modal-panel">
<div className="flex items-center justify-between border-b border-white/10 px-4 py-3"><div><h3 className="text-sm font-bold text-white/90">Notifications</h3><p className="text-[11px] text-white/45">{unread?unread+' unread':'সব notification দেখা হয়েছে'}</p></div><div className="flex items-center gap-1">{unread>0&&<button onClick={()=>void markRead()} className="rounded-lg px-2 py-1 text-[11px] font-semibold text-[#ABD2FA] hover:bg-white/[0.06]">Mark all read</button>}<button onClick={()=>setOpen(false)} className="rounded-lg p-1.5 text-white/45 hover:bg-white/[0.06]" aria-label="Close notifications"><X size={16}/></button></div></div>
<div className="max-h-[min(70vh,420px)] overflow-y-auto overscroll-contain">{loading&&!items.length?<div className="flex items-center justify-center py-10"><Loader2 className="animate-spin text-slate-400" size={20}/></div>:items.length?items.map(item=><button key={item._id} onClick={()=>!item.read&&void markRead(item._id)} className={'flex w-full gap-3 border-b border-white/10 px-4 py-3 text-left transition hover:bg-white/[0.05] '+(item.read?'bg-transparent':'bg-[#1B2CC1]/15')}><span className={'mt-0.5 flex h-8 w-8 shrink-0 items-center justify-center rounded-full '+(item.read?'bg-white/[0.06] text-white/40':'bg-[#1B2CC1]/30 text-[#ABD2FA]')}>{item.read?<Check size={15}/>:<Bell size={15}/>}</span><span className="min-w-0 flex-1"><span className="block text-[13px] font-bold text-white/90">{item.title}</span><span className="mt-0.5 block whitespace-pre-line text-[12px] leading-5 text-white/55">{item.message}</span><span className="mt-1 block text-[10px] text-slate-400">{relativeTime(item.createdAt)}</span></span></button>):<div className="px-5 py-12 text-center"><Bell size={25} className="mx-auto text-white/25"/><p className="mt-2 text-sm font-semibold text-white/70">No notifications</p><p className="mt-1 text-xs text-slate-400">আপনার নতুন report বা update এখানে দেখা যাবে।</p></div>}</div>
</motion.div>}</AnimatePresence></div>;
}