'use client';
import {useEffect,useState} from 'react';
import {LoadingSpinner} from '@/components/LoadingSpinner';

type AdminUser={_id:string;name?:string;email?:string;role:string;status:string;createdAt:string};
export default function AdminUsers(){
 const[data,setData]=useState<AdminUser[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState('');const[busyId,setBusyId]=useState<string|null>(null);
 async function load(){setLoading(true);try{const r=await fetch('/api/admin/users');const j=await r.json();if(!r.ok)throw new Error(j.error||'Failed to load users');setData(j.users)}catch(e:any){setError(e.message||'Failed to load users')}finally{setLoading(false)}}
 useEffect(()=>{load()},[]);
 async function toggle(id:string,status:string){setError('');setBusyId(id);try{const r=await fetch(`/api/admin/users/${id}`,{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({status:status==='ACTIVE'?'SUSPENDED':'ACTIVE'})});const j=await r.json();if(!r.ok)throw new Error(j.error||'Update failed');setData(v=>v.map(u=>String(u._id)===id?{...u,status:j.user.status}:u))}catch(e:any){setError(e.message||'Update failed')}finally{setBusyId(null)}}
 return <div><h1 className="text-[30px] font-semibold tracking-[-.035em]">Users</h1><p className="mt-2 text-slate-500">Review account access. Admin accounts cannot be suspended from this screen.</p>{error&&<div className="mt-4 rounded-xl border border-red-400/30 bg-red-50 p-3 text-sm text-red-700">{error}</div>}<div className="mt-6 overflow-x-auto rounded-xl border border-black/[.07] bg-white/80">{loading?<div className="flex items-center justify-center p-8"><LoadingSpinner label="Loading users…"/></div>:<table className="w-full min-w-[760px] text-left text-sm"><thead className="text-slate-500"><tr><th className="p-4">Name</th><th className="p-4">Email</th><th className="p-4">Role</th><th className="p-4">Status</th><th className="p-4">Created</th><th className="p-4">Action</th></tr></thead><tbody>{data.map(u=><tr key={String(u._id)} className="border-t border-black/[.07]"><td className="p-4">{u.name}</td><td className="p-4">{u.email}</td><td className="p-4">{u.role}</td><td className="p-4">{u.status}</td><td className="p-4">{new Date(u.createdAt).toLocaleDateString('en-BD')}</td><td className="p-4">{u.role==='ADMIN'?<span className="text-slate-500">Protected</span>:<button onClick={()=>toggle(String(u._id),u.status)} disabled={busyId===String(u._id)} aria-busy={busyId===String(u._id)} className="rounded-lg border border-black/[.10] px-3 py-2 hover:bg-black/[.05]">{busyId===String(u._id)?<LoadingSpinner label="Updating…"/>:(u.status==='ACTIVE'?'Suspend':'Activate')}</button>}</td></tr>)}</tbody></table>}</div></div>
}
