'use client';
import Link from 'next/link';
import {useEffect,useState} from 'react';
import {ArrowRight,BookOpen,Boxes,WalletCards,AlertTriangle,Mic} from 'lucide-react';
import {apiRequest} from '@/lib/api-client';
import {useToast} from '@/components/ToastProvider';

type DashboardData={parties:number;products:number;lowStock:number;balances?:{receivable?:number};recent?:Array<{_id:string;partyId?:{name:string};productId?:{name:string};type:string;amount?:number;timestamp:string}>;};
export default function DashboardPage(){const[d,setD]=useState<DashboardData|null>(null);const[loading,setLoading]=useState(true);const[error,setError]=useState('');const {toast}=useToast();const load=async()=>{try{setError('');const data=await apiRequest<DashboardData>('/api/dashboard');setD(data)}catch(e){setError(e instanceof Error?e.message:'Could not load dashboard');toast('Dashboard data could not be loaded.','error')}finally{setLoading(false)}};useEffect(()=>{load();const h=()=>load();window.addEventListener('talikhata:refresh',h);return()=>window.removeEventListener('talikhata:refresh',h)},[]);if(loading)return <div className="mx-auto max-w-6xl animate-pulse"><div className="h-52 rounded-2xl bg-slate-200"/><div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{Array.from({length:4}).map((_,i)=><div key={i} className="h-28 rounded-2xl bg-slate-200"/> )}</div></div>;return <div className="mx-auto max-w-6xl">{error&&<div className="mb-5 flex items-center justify-between rounded-2xl border border-red-200 bg-red-50 p-4 text-sm text-red-700"><span>{error}</span><button className="btn-secondary" onClick={load}>Retry</button></div>}<div className="rounded-2xl border bg-white p-6 shadow-sm md:p-8"><div className="flex flex-col justify-between gap-5 md:flex-row"><div><p className="flex items-center gap-2 text-sm font-semibold text-emerald-700"><Mic size={16}/> Voice-first shop management</p><h1 className="mt-2 text-3xl font-bold">আজকের হিসাব</h1><p className="mt-2 text-slate-500">Your shop at a glance. Add records by form or simply speak.</p></div><Link href="/dashboard/sales" className="btn-primary self-start">Add transaction <ArrowRight size={17}/></Link></div><div className="mt-7 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Card icon={<BookOpen/>} title="Parties" value={d?.parties??0} href="/dashboard/parties"/><Card icon={<Boxes/>} title="Products" value={d?.products??0} href="/dashboard/products"/><Card icon={<WalletCards/>} title="পাবো" value={`৳${Number(d?.balances?.receivable||0).toLocaleString()}`} href="/dashboard/parties"/><Card icon={<AlertTriangle/>} title="Low stock" value={d?.lowStock??0} href="/dashboard/products"/></div></div><div className="mt-6 rounded-2xl border bg-white p-5"><div className="flex items-center justify-between"><h2 className="font-semibold">Recent activity</h2><Link href="/dashboard/transactions" className="text-sm font-semibold text-emerald-700">View all</Link></div><div className="mt-4 space-y-2">{d?.recent?.map(r=><div key={r._id} className="flex items-center justify-between rounded-xl border p-3"><div><p className="font-medium">{r.partyId?.name||r.productId?.name||r.type}</p><p className="text-xs text-slate-500">{new Date(r.timestamp).toLocaleString('en-BD')} • {r.type}</p></div><span className="font-semibold">৳{Number(r.amount||0).toLocaleString()}</span></div>)}{!d?.recent?.length&&<p className="py-10 text-center text-slate-400">No recent activity.</p>}</div></div></div>}
function Card({icon,title,value,href}:{icon:React.ReactNode;title:string;value:React.ReactNode;href:string}){return <Link href={href} className="rounded-2xl border p-5 transition hover:-translate-y-0.5 hover:shadow-md"><div className="text-emerald-600">{icon}</div><p className="mt-3 text-sm text-slate-500">{title}</p><p className="mt-1 text-2xl font-bold">{value}</p></Link>}
